spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feng_note
    username: root
    password: 123456
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    content-type: text/html; charset=utf-8
    cache: false   
mybatis:
  type-aliases-package: com.feng.note
  
server:
  port: 8081 